name = "andreimaxim-com"
compatibility_date = "2024-12-05"
assets = { directory = "_site" }

[env.production]
name = "andreimaxim-com"
routes = [
  { pattern = "andreimaxim.com/*", zone_name = "andreimaxim.com" },
  { pattern = "www.andreimaxim.com/*", zone_name = "andreimaxim.com" }
]
